name = "blog-joshua-wales"
type = "webpack"
account_id = "f1307d32ef6e901ab1f027a47c3e646c"
workers_dev = true
route = ""
zone_id = "66c67048116214d406bed3a542359a81"

[site]
bucket = "./public"
entry-point = "workers-site"

# environment configuration
[env.staging]
name = "blog-joshua-wales-staging"
route = "staging.blog.joshua.wales/*"

# environment configuration
[env.production]
name = "blog-joshua-wales-production"
route = "blog.joshua.wales/*"

